# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=50)),
                ('trigger', models.CharField(max_length=20)),
                ('bitrate', models.IntegerField()),
                ('bandwidth', models.IntegerField()),
                ('media_seq', models.IntegerField()),
                ('width', models.IntegerField()),
                ('load_time', models.FloatField()),
                ('container_height', models.IntegerField()),
                ('container_width', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
                ('position', models.FloatField()),
                ('fullscreen', models.BooleanField()),
                ('quality_label', models.CharField(max_length=20)),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_hash', models.CharField(max_length=32, unique=True)),
                ('valid_host', models.CharField(max_length=15)),
                ('expiration', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('episode', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField()),
                ('device_type', models.CharField(max_length=40)),
                ('user_agent', models.CharField(max_length=500)),
                ('ip_source', models.CharField(max_length=15)),
                ('user_name', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('idp', models.CharField(max_length=50)),
                ('idp_name', models.CharField(blank=True, max_length=200)),
                ('media_id', models.CharField(max_length=10)),
                ('media_filename', models.CharField(max_length=200)),
                ('media_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='play_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatra_player.Play'),
        ),
    ]
